### ISSUE TITLE
Your code is not worthy of being called "God" 

### ISSUE THREAD

**Issue by JordanMicahBennett** [zond/god#24]
By the way, [my "God"](https://github.com/JordanMicahBennett/God) is an Edward Witten inspired, [Supersymmetric learning algorithm](https://github.com/JordanMicahBennett/Supersymmetric-artificial-neural-network).

1. Gods ought to be learning algorithms, not basic code as you currently have in your repo.
2. Notably I am an atheist, so I observe that Gods as defined [within the realm of artificial general intelligence](https://m.youtube.com/watch?feature=youtu.be&t=849&v=8nt3edWLgIg) ought ***not*** to be worshipped and [ought to be atheism compatible](https://www.researchgate.net/publication/316662636_A_scientific_redefinition_of_God_by_an_atheist)!!

**Comment by zond** [comment]
It's not called "God", it's called "god", and it's an acronym for "go database".
